
#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 9411
  servlet:
    context-path: ~
  tomcat:
    uri-encoding: UTF-8
    
#======================================#
#========== Cloud settings ============#
#======================================#

# 服务注册
eureka:

  # 实例设置
  instance:
    # 实例主机名称
    hostname: 127.0.0.1
    # 实例是否允许使用IP
    preferIpAddress: false
    # 实例状态监控参数
    statusPageUrlPath: ${server.servlet.context-path}
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health

  # 客户端设置
  client:
    # 注册中心地址（集群时指定另外一个注册中心地址）
    serviceUrl.defaultZone: http://127.0.0.1:8970/eureka/

#======================================#
#========== Spring settings ===========#
#======================================#

spring:
  cloud:
    
    # Consul 服务发现
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        healthCheckPath: ${server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
        
    # 服务注册和配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      
  # 应用程序名称
  application:
    name: jeesite-cloud-zipkin

# Web 配置
management:
  metrics:
    web:
      server:
        auto-time-requests: false
        
# 日志配置
logging:
  config: classpath:config/logback-spring.xml